dist: bionic

language:
  - generic

before_install:
  - docker-compose build
  - docker images
  - docker-compose -f docker-compose.yml -f docker-compose.debug.yml up -d
  - docker-compose ps

script:
  - sleep 3
  - curl http://localhost:8002
  - docker-compose logs --no-color
  - docker logs chtsh
  - CHTSH_URL=http://localhost:8002 CHEATSH_TEST_STANDALONE=NO bash tests/run-tests.sh
