# Compose override to add --debug option to bin/srv.py
# call to print tracebacks on errors to stdout.
#
# See https://docs.docker.com/compose/extends/
version: '2'
services:
  app:
    command: "--debug"
